### ISSUE TITLE
.py binary file cannot be executed in process_in_parallel func in subprocess.py 

### ISSUE THREAD

**Issue by xuchao1688** [facebookresearch/Detectron#295]
### Expected results

When go  test_net.py, the subprocess should execute the cmd parallelly in GPUS, and save the result to the file.

### Actual results

When run for test net, in utils/subprocess.py
The cmd
        cmd = '{binary} --range {start} {end} --cfg {cfg_file} NUM_GPUS 1'
need python environment to execute {binary} file.
However, in some machines, python command file cannot be found autoly while they actually have python installed.
You should explictly give the python command before {binary} file to ensure the cmd can be correctly executed.

**Comment by xuchao1688** [comment]
OS: Ubuntu 14.04

**Comment by rbgirshick** [comment]
`python` needs to be in your `$PATH`. We won't support searching for arbitrary locations and guessing which one to use. You should fix this on your end.

**Comment by xuchao1688** [comment]
Actually, although `python` is already in my `$PATH`, your cmd str still doesn't work. It needs to explictly use `python `command in the cmd str. Ant it's why i open this issue for you.

**Comment by rbgirshick** [comment]
This seems to work for most users. Please provide a clearer explanation and show the actual error message.

**Comment by xuchao1688** [comment]
Thanks for replying. If i don't change your source code, and just run the multi_gpu training with 2 P40 gpus as mentioned at the bottom of  `GETTING_STARTED.md`. When the training process goes to test, it throwes an error : 
```
INFO subprocess.py: 117: # ---------------------------------------------------------------------------- #
: No such file or directory
Traceback (most recent call last):
...
  assert ret == 0, 'Range subprocess failed (exit code: {})'.format(ret)
AssertionError: Range subprocess failed (exit code: 127)
```
It's a puzzling error since it doesn't say which file cannot be found. Fortunately, I find the hint in the `detection_range_0_2500.stdout` file for test result in `OUTPUT_DIR `directory. It says that
`/usr/bin/env: python2: No such file or directory`.
Howerver, I actually has `python2` in `$PATH` in my machine. I think the reason may be the `.py` python script (specially, `tools/test_net.py`) doesn't has `#!/bin/python2` in the front of the whole paragraph. So I just explictly write the `python2` command before `.py` binary file (specially, tools/test_net.py) in cmd str. Then, without any change else, I restart the training and it works.

**Comment by kebinC** [comment]
It seems that 'doc2unix tools/test_net.py' can solve.
