### ISSUE TITLE
【Train issue with caffe2 detectron】Aborted at 1523501813 (unix time) try "date -d @1523501813" if you are using GNU date *** PC: @ 0x7fa35103733a (unknown) 

### ISSUE THREAD

**Issue by Shentongmo** [facebookresearch/Detectron#359]
I try to run resnet50_trainer.py to build my model by using 100 images, but I get the following error messages. My train method is drawn on the following web, https://github.com/royhuang9/Detectron. How to fix the error and run correctly using Caffe2? I am not sure if this is a Caffe2 issue.
Train command:
python2 tools/train_net.py --cfg experiments/e2e_faster_rcnn_resnet-50-FPN_pascal2007.yaml OUTPUT_DIR experiments/output
Error meassage:
json_stats: {"accuracy_cls": 1.000000, "eta": "1:59:55", "iter": 26200, "loss": 0.000865, "loss_bbox": 0.000183, "loss_cls": 0.000680, "loss_rpn_bbox_fpn2": 0.000000, "loss_rpn_bbox_fpn3": 0.000000, "loss_rpn_bbox_fpn4": 0.000003, "loss_rpn_bbox_fpn5": 0.000003, "loss_rpn_bbox_fpn6": 0.000000, "loss_rpn_cls_fpn2": 0.000000, "loss_rpn_cls_fpn3": 0.000005, "loss_rpn_cls_fpn4": 0.000004, "loss_rpn_cls_fpn5": 0.000002, "loss_rpn_cls_fpn6": 0.000000, "lr": 0.002500, "mb_qsize": 64, "mem": 2451, "time": 0.212877}
*** Aborted at 1523501813 (unix time) try "date -d @1523501813" if you are using GNU date ***
PC: @ 0x7fa35103733a (unknown)
*** SIGSEGV (@0x0) received by PID 6778 (TID 0x7fa2edffb700) from PID 0; stack trace: ***
@ 0x7fa351390390 (unknown)
@ 0x7fa35103733a (unknown)
@ 0x7fa351039184 __libc_malloc
@ 0x7fa348101c51 (unknown)
@ 0x7fa348164232 (unknown)
@ 0x7fa3481642ea (unknown)
@ 0x7fa3481f29d4 (unknown)
@ 0x7fa3481f2da0 (unknown)
@ 0x4c195b PyEval_EvalFrameEx
@ 0x4c136f PyEval_EvalFrameEx
@ 0x4b9ab6 PyEval_EvalCodeEx
@ 0x4d54b9 (unknown)
@ 0x4eebee (unknown)
@ 0x4a577e PyObject_Call
@ 0x4c5e10 PyEval_CallObjectWithKeywords
@ 0x7fa33adca3d0 pybind11::detail::object_api<>::operator()<>()
@ 0x7fa33adcbb51 caffe2::python::PythonOpBase<>::RunOnDevice()
@ 0x7fa33ad932cb caffe2::Operator<>::Run()
@ 0x7fa33addce3a _ZN6caffe213GPUFallbackOpINS_6python8PythonOpINS_10CPUContextELb0EEENS_11SkipIndicesIJEEEE11RunOnDeviceEv
@ 0x7fa33add95d5 caffe2::Operator<>::Run()
@ 0x7fa336bcef0a caffe2::DAGNet::RunAt()
@ 0x7fa336bcdbbe caffe2::DAGNetBase::WorkerFunction()
@ 0x7fa34a5cbc80 (unknown)
@ 0x7fa3513866ba start_thread
@ 0x7fa3510bc41d clone
@ 0x0 (unknown)

**Comment by sefira** [comment]
I meet the same error when training FPN using detectrion... after 18880 iterations

```
json_stats: {"accuracy_cls": 0.882812, "eta": "4:46:10", "iter": 18860, "loss": 0.762724, "loss_bbox": 0.204965, "loss_cls": 0.371853, "loss_rpn_bbox_fpn2": 0.024563, "loss_rpn_bbox_fpn3": 0.005467, "loss_rpn_bbox_fpn4": 0.004693, "loss_rpn_bbox_fpn5": 0.017579, "loss_rpn_bbox_fpn6": 0.000000, "loss_rpn_cls_fpn2": 0.037424, "loss_rpn_cls_fpn3": 0.011300, "loss_rpn_cls_fpn4": 0.007033, "loss_rpn_cls_fpn5": 0.002922, "loss_rpn_cls_fpn6": 0.000000, "lr": 0.000500, "mb_qsize": 64, "mem": 3754, "time": 1.541344}
json_stats: {"accuracy_cls": 0.892578, "eta": "4:45:31", "iter": 18880, "loss": 0.681168, "loss_bbox": 0.168957, "loss_cls": 0.337945, "loss_rpn_bbox_fpn2": 0.061520, "loss_rpn_bbox_fpn3": 0.005756, "loss_rpn_bbox_fpn4": 0.003855, "loss_rpn_bbox_fpn5": 0.008959, "loss_rpn_bbox_fpn6": 0.000000, "loss_rpn_cls_fpn2": 0.047910, "loss_rpn_cls_fpn3": 0.014308, "loss_rpn_cls_fpn4": 0.005937, "loss_rpn_cls_fpn5": 0.002410, "loss_rpn_cls_fpn6": 0.000000, "lr": 0.000500, "mb_qsize": 64, "mem": 3754, "time": 1.540636}
json_stats: {"accuracy_cls": 0.889176, "eta": "4:44:53", "iter": 18900, "loss": 0.712495, "loss_bbox": 0.204505, "loss_cls": 0.336890, "loss_rpn_bbox_fpn2": 0.034822, "loss_rpn_bbox_fpn3": 0.006376, "loss_rpn_bbox_fpn4": 0.003501, "loss_rpn_bbox_fpn5": 0.006411, "loss_rpn_bbox_fpn6": 0.000000, "loss_rpn_cls_fpn2": 0.043415, "loss_rpn_cls_fpn3": 0.012726, "loss_rpn_cls_fpn4": 0.006156, "loss_rpn_cls_fpn5": 0.003171, "loss_rpn_cls_fpn6": 0.000000, "lr": 0.000500, "mb_qsize": 64, "mem": 3754, "time": 1.539935}
*** Aborted at 1523575095 (unix time) try "date -d @1523575095" if you are using GNU date ***
PC: @     0x7ffcbf631356 _int_malloc

```

**Comment by Shentongmo** [comment]
I have fixed the problem. I think you should change the suitable value of batch_size or max_iter. Have a try.

**Comment by sefira** [comment]
@Shentongmo Thanks for your reply!

What do you mean by saying “the suitable value of batch_size or max_iter”?
I run the defualt config tutorial_2gpu_e2e_faster_rcnn_R-50-FPN.yaml in COCO17 dataset, where the MAX_ITER: 30000 BATCH_SIZE_PER_IM: 256 IMS_PER_BATCH: 2

Do you have a heuristic method to choose “the suitable value of batch_size or max_iter”? What is the exactly problem bought by batch_size and max_iter in your try?

Thanks again~

**Comment by blateyang** [comment]
I meet the same problem and I have tried different batch_size from 128 to 512 as well as different max_iter. However, it doesn't work for me. The problem still exists.  @Shentongmo Can you share your method on how to change the suitable value or batch_size or max_iter?  Thanks in advance!
```
json_stats: {"accuracy_cls": 0.996094, "eta": "2:06:31", "iter": 27560, "loss": 0.020171, "loss_bbox": 0.005471, "loss_cls": 0.009772, "loss_rpn_bbox_fpn2": 0.000000, "loss_rpn_bbox_fpn3": 0.000000, "loss_rpn_bbox_fpn4": 0.000000, "loss_rpn_bbox_fpn5": 0.000422, "loss_rpn_bbox_fpn6": 0.000000, "loss_rpn_cls_fpn2": 0.000000, "loss_rpn_cls_fpn3": 0.000001, "loss_rpn_cls_fpn4": 0.000002, "loss_rpn_cls_fpn5": 0.000019, "loss_rpn_cls_fpn6": 0.000000, "lr": 0.000250, "mb_qsize": 64, "mem": 4009, "time": 0.178870}
*** Aborted at 1525421992 (unix time) try "date -d @1525421992" if you are using GNU date ***
PC: @     0x7f81c7321ff1 (unknown)
*** SIGSEGV (@0x19) received by PID 11091 (TID 0x7f813c844700) from PID 25; stack trace: ***
    @     0x7f81c767d390 (unknown)
    @     0x7f81c7321ff1 (unknown)
    @     0x7f81c732653c cfree
    @     0x7f81be71cdef npy_free_cache
    @     0x7f81be720032 array_dealloc
    @           0x4c1732 PyEval_EvalFrameEx
    @           0x4c136f PyEval_EvalFrameEx
    @           0x4b9ab6 PyEval_EvalCodeEx
    @           0x4d54b9 (unknown)
    @           0x4eebee (unknown)
    @           0x4a577e PyObject_Call
    @           0x4c5e10 PyEval_CallObjectWithKeywords
    @     0x7f81bbafefb7 pybind11::detail::object_api<>::operator()<>()
    @     0x7f81bbb00e01 caffe2::python::PythonOpBase<>::RunOnDevice()
    @     0x7f81bbac655b caffe2::Operator<>::Run()
    @     0x7f81bbb130b8 _ZN6caffe213GPUFallbackOpINS_6python8PythonOpINS_10CPUContextELb0EEENS_11SkipIndicesIJEEEE11RunOnDeviceEv
    @     0x7f81bbb0f675 caffe2::Operator<>::Run()
    @     0x7f819da3998a caffe2::DAGNet::RunAt()
    @     0x7f819da3887c caffe2::DAGNetBase::WorkerFunction()
    @     0x7f81c0be6c80 (unknown)
    @     0x7f81c76736ba start_thread
    @     0x7f81c73a941d clone
    @                0x0 (unknown)
```

**Comment by drcege** [comment]
I have the same problem. Using the same cfg, mostly the training fininshed without any error, but sometimes the abortion occur accidentally.

**Comment by pengyongrong** [comment]
do you have solve it . i have the same condition of you
